stages:
  - build
  - deploy

.docker:
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
  tags:
    - docker

.build:
  stage: build
  extends: .docker
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG || true
    - docker pull $IMAGE_NAME:$CI_COMMIT_REF_SLUG || true
    - docker build --target build
      --build-arg ROOT_URL=${ROOT_URL}
      --cache-from $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG
      -t $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG
      .
    - docker push $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG
    - docker build --target server
      --cache-from $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG
      --cache-from $IMAGE_NAME:$CI_COMMIT_REF_SLUG
      -t $IMAGE_NAME:$CI_COMMIT_SHA
      -t $IMAGE_NAME:$CI_COMMIT_REF_SLUG
      .
    - docker push $IMAGE_NAME:$CI_COMMIT_SHA
    - docker push $IMAGE_NAME:$CI_COMMIT_REF_SLUG

build review:
  extends: .build
  variables:
    ROOT_URL: https://jreinert.gitlab.io/samuwagen-website/
    IMAGE_NAME: $CI_REGISTRY_IMAGE/review
  only:
    - branches
  except:
    - master

build staging:
  extends: .build
  variables:
    ROOT_URL: https://staging.www.samuwagen.com/
    IMAGE_NAME: $CI_REGISTRY_IMAGE/staging
  only:
    - master

build production:
  extends: .build
  variables:
    ROOT_URL: https://www.samuwagen.com/
    IMAGE_NAME: $CI_REGISTRY_IMAGE/production
  only:
    - master

.deploy:
  stage: deploy
  variables:
    DOMAINS: ${CI_ENVIRONMENT_SLUG}.www.samuwagen.com
  environment:
    url: https://${CI_ENVIRONMENT_SLUG}.www.samuwagen.com
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker stack deploy --with-registry-auth -c docker-compose.yml samuwagen-${CI_ENVIRONMENT_SLUG}
  tags:
    - deploy

pages:
  stage: deploy
  extends: .docker
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/review
  environment:
    name: review/${CI_COMMIT_REF_NAME}
    url: https://jreinert.gitlab.io/samuwagen-website
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG
    - CONTAINER=$(docker create $IMAGE_NAME/build:$CI_COMMIT_REF_SLUG)
    - docker cp $CONTAINER:/build ./public
    - docker rm $CONTAINER
  artifacts:
    paths:
      - public
  only:
    - branches
  except:
    - master

deploy staging:
  extends: .deploy
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/staging
  environment:
    name: staging
  only:
    - master

deploy production:
  extends: .deploy
  variables:
    IMAGE_NAME: $CI_REGISTRY_IMAGE/production
    DOMAINS: samuwagen.com,www.samuwagen.com
    REDIRECT_REGEX: ^https://samuwagen.com/(.*)
    REDIRECT_REPLACEMENT: https://www.samuwagen.com/$$1
  environment:
    name: production
    url: https://www.samuwagen.com
  when: manual
  only:
    - master
