baseURL: https://www.samuwagen.com/
DefaultcontentLanguage: fi
copyright: SamuWagen
title: SamuWagen
sectionPagesMenu: main
theme: ananake
disableKinds:
  - taxonomy
  - taxonomyTerm

languages:
  fi:
    languageName: Suomi
    weight: 1
  en:
    languageName: English
    weight: 2
  de:
    languageName: Deutsch
    weight: 3
