baseURL: https://www.samuwagen.com/
languageCode: en-us
copyright: SamuWagen
title: SamuWagen
sectionPagesMenu: main
theme: simplicity
disableKinds:
  - taxonomy
  - taxonomyTerm
enableRobotsTXT: true
